### PR TITLE
Finish 405 responses to avoid hanging

### PR DESCRIPTION
**Pull request by turt2live**
### Pull Request Checklist

- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)

### CODE REVIEW

**Comment by turt2live** [comment]
test failure appears to be not my fault

**Comment by turt2live** [comment]
this patch doesn't appear to work: it still hangs for me. I don't know why.

**Comment by kegsay** [comment]
I was going to say that this should make no difference. `ServeHTTP` simply asks that you call `WriteHeader`, it doesn't mandate you set headers, read the req body or set a response body.

**Comment by kegsay** [comment]
Nothing to do here.

**Pull request closed without merging**
